### PR TITLE
Update syntax

### PR DESCRIPTION
**Pull request by amelieled**
Update LP syntax but there are 3 lost proofs.

### CODE REVIEW

**Comment by QGarchery** [comment]
Really cool !

Why are those proofs difficult to translate ? I can take a look at them this week-end

**Comment by amelieled** [comment]
```
Why are those proofs difficult to translate ? I can take a look at them this week-end.
```
I don't know if the problem comes from LP or a misunderstanding from my side of the new syntax. 
I think it's possible to fix the problem, but I need to understand deeply your formalization.
(The three proofs are very similar btw)

**Comment by amelieled** [comment]
Moreover, maybe it's not a good idea to merge this PR soon.
There is at least one "bug" in LP with the curly brackets: see https://github.com/Deducteam/lambdapi/issues/894.
But this issue #894 isn't a priority for Frédéric.

**Comment by amelieled** [comment]
Moreover, maybe it's not a good idea to merge this PR soon.
There is at least one "bug" in LP with the curly brackets: see https://github.com/Deducteam/lambdapi/issues/894.
But this issue #894 isn't a priority for Frédéric.

**Comment by amelieled** [comment]
Moreover, maybe it's not a good idea to merge this PR soon.
There is at least one "bug" in LP with the curly brackets: see https://github.com/Deducteam/lambdapi/issues/894.
But this issue #894 isn't a priority for Frédéric.

**Comment by QGarchery** [comment]
Closing it as it is was rebased and included in master. See also https://github.com/fblanqui/lib/pull/1

Thanks again for your work :)

**Pull request closed without merging**
